name: Main

on: 
  release:
    types: [prereleased]

env:
  GITHUB_PACKAGE_URL: 'https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json'
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: 资源构建
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
  deploy:
    name: 部署到GitHub包
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: 下载组件
      uses: actions/download-artifact@v2
      with:
        name: release-nuget

    - name: 设置Nuget
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: latest

    - name: 添加GitHub包源
      run: nuget sources Add -Name GitHub -Source ${{env.GITHUB_PACKAGE_URL}} -UserName ${{ github.repository_owner }} -Password ${{ secrets.GITHUB_TOKEN }}

    - name: 推送到GitHub包
      run: nuget push **/*.txt -source GitHub -SkipDuplicate

    - name: 将测试报告添加到发布
      uses: irongut/EditRelease@v1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        id: ${{ github.event.release.id }}
        body: "Released to GitHub Packages."
        files: "aaa.txt"
