name: Main

on: 
  release:
    types: [created]

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.100'

      - name: Build
        run: |
          cd src
          dotnet build
      - name: CI Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Plugin
          path: |
            ./src/bin/Debug/net6.0/
      - name: CI Artifact
        uses: actions/upload-artifact@v3
        with:
          name: NuGet Package
          path: |
            ./src/bin/Debug/*.symbols.nupkg
            
      - name: Set env output and package
        id: setenvo
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          dotnet nuget push src/bin/Debug/*.symbols.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
          echo "TAG_NAME=$(git rev-list --count HEAD)" >> $env:GITHUB_OUTPUT
          Copy-Item ./src/bin/Debug/net6.0/* ./
          tar cvf Artifact.tar Chireiden.TShock.Omni.* LICENSE.txt,aaa.txt README.md
          Compress-Archive -Path Chireiden.TShock.Omni.*,LICENSE.txt,aaa.txt,README.md Artifact.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          prerelease: true
          tag_name: v${{ steps.setenvo.outputs.TAG_NAME }}
          name: Release v${{ steps.setenvo.outputs.TAG_NAME }}
          files: |
            Artifact.tar
            Artifact.zip
