name: Build + Deploy

on: 
  release:
    types: [prereleased]
    
env:
  GITHUB_PACKAGE_URL: 'https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json'
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: 资源构建
    steps:
    - name: 校验
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: 安装.NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: 将包修改添加到发布
      uses: irongut/EditRelease@v1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        id: ${{ github.event.release.id }}
        body: "这玩意只能修改文本和标题不能改文件"
        files: "aaa.txt"
        
    - name: 上传资源
      uses: svenstaro/upload-release-action@v2
      with:
       repo_token: ${{ secrets.GITHUB_TOKEN }}
       file: aaa.txt
       asset_name: 666.txt
       tag: ${{ github.ref }}
       overwrite: true
       body: "This is my release text"
