on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Attach binaries
      run: ./build.sh
      
      - name: Upload Attach binaries
      uses: actions/upload-artifact@v2
      with:
        name: Attach binaries
        path: path/to/attach/binaries
