name: prereleased
on: 
  release:
    types: [prereleased]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    name: 修改备注
    steps:
     - uses: actions/checkout@v3
       with:
          submodules: 'recursive'
     - name: 将包修改添加到发布
       uses: irongut/EditRelease@v1.2.0
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         id: ${{ github.event.release.id }}
         body: "⚠Please pay attention to backup. The Pre-release version may cause your data loss."
